version: '3'

services:
  jupyter:
    container_name: jupyter_alert
    build: ./
    volumes:
      # - ./:/home/jovyan/docker
      # - ./requirements.txt:/home/jovyan/work
      - ../plots/:/home/jovyan/work/plots
      - ../python_scripts:/home/jovyan/work/python_scripts
      - ../notebooks/:/home/jovyan/work/notebooks
      - ../amber_outputs:/home/jovyan/work/amber_outputs
    ports:
      - "8888:8888"
    command: "sm-python-bi; start-notebook.sh --NotebookApp.token='b2cd90e9a0dd'"
