version: '3'

services:
  redis:
    container_name: redis_alert
    image: redis:5.0-rc3
    restart: always
    ports:
     - '6379:6379'
  db:
    container_name: mysql_alert
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: alert_dev
      MYSQL_USER: alert_web
      MYSQL_PASSWORD: test-password#1
    ports:
       - "40001:3306"
  web:
    container_name: dg_alert
    build: ./
    command: >
      bash -c "mkdir -p log
      && python3 development-manage.py migrate
      && python3 development-manage.py setup
      && python3 development-manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
      - ./alert_web/static/:/static/
      - ./media/:/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery:
    container_name: celery_alert
    build: ./
    command: >
      bash -c "mkdir -p log
      && celery -A alert worker -l info"
    volumes:
      - ./:/code
    depends_on:
      - db
      - redis
