"""
Distributed under the MIT License. See LICENSE.txt for more info.
"""

# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-12 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_web', '0003_auto_20180612_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagestore',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
