"""
Distributed under the MIT License. See LICENSE.txt for more info.
"""

# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-15 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_web', '0004_auto_20180612_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
